version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run build
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: |
          npm ci
          npm run build
      - add_ssh_keys:
          fingerprints:
            - "30:8d:bf:0a:d3:e3:d2:33:d7:46:23:5f:ba:d7:26:fb"
      - run: |
          cd dist
          git init
          git config user.name "$(cd .. && git log -1 --format='%cn')"
          git config user.email "$(cd .. && git log -1 --format='%ce')"
          git remote add origin https://github.com/buttons/buttons.github.io.git
          git fetch origin master
          git reset origin/master
          git add -A
          git commit -m "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME@$CIRCLE_SHA1 $(cd .. && git log -1 --format='%B')"
          git push origin master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
